AWS_ACCESS_KEY_ID: 1DHMT66Z5YHWFFCN21G2
AWS_SECRET_ACCESS_KEY: 78prB8qxICQYw4OKFuMKLPWxz2sN4U7pX/CB8pXY
AWS_SSH_PRIVKEY: /vagrant/salt/kstaken-dev.pem
AWS_KEYPAIR_NAME: kstaken-dev
AWS_SSH_PRIVKEY: /vagrant/salt/kstaken-dev.pem